package SimpleSchema.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.INamedConcept_BehaviorDescriptor;

public interface Type_BehaviorDescriptor extends INamedConcept_BehaviorDescriptor {
}
