package SimpleSchema.textGen;

/*Generated by MPS */

import jetbrains.mps.textGen.SNodeTextGen;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;

public class Element_TextGen extends SNodeTextGen {
  public void doGenerateText(SNode node) {
    this.append("<element name=\"");
    this.append(SPropertyOperations.getString(node, "name"));
    this.append("\">");
  }
}
