package SimpleSchema.textGen;

/*Generated by MPS */

import jetbrains.mps.textGen.SNodeTextGen;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;

public class Schema_TextGen extends SNodeTextGen {
  public void doGenerateText(SNode node) {
    this.append("<schema>");
    this.appendNewLine();
    this.increaseDepth();
    this.indentBuffer();
    appendNode(SLinkOperations.getTarget(node, "rootElement", true));
    this.appendNewLine();
    for (SNode type : ListSequence.fromList(SLinkOperations.getTargets(node, "types", true))) {
      this.indentBuffer();
      appendNode(type);
      this.appendNewLine();
    }
    this.decreaseDepth();
    this.append("</schema>");
    this.appendNewLine();
  }

  public String getExtension(SNode node) {
    return ".xsd";
  }
}
